name: Validate and Update Leaderboard

on:
  pull_request:
    paths:
      - "*_task1.yaml"  # Trigger for any task submission file

jobs:
  validate-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install pyyaml

    - name: Validate Submission and Update Leaderboard
      run: |
        # Find the submitted file (assuming only one such file is submitted per PR)
        FILE=$(ls *_task1.yaml)
        python validate_submission.py "$FILE"

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add task1/ leaderboard.yaml
        git commit -m "Updated leaderboard and task folder for $FILE"
        git push
